### ISSUE TITLE
charts export size

### ISSUE THREAD

**Issue by jig78** [ideonate/nb2xls#2]
Is there any way to export the charts in a larger size in excel. I am able to use the package on all my notebooks but chart export size seems too small and I have to manually increase each chart size in excel. Please let me know if I missed anything? 
Thanks for your work on this, its great!

**Comment by danlester** [comment]
Thank you for your message. Great to hear you like the project!

Please could you share a sample ipynb notebook so I can see for myself what's going in and what comes out? Of course, please cut out any sensitive data - I'm just looking for a notebook with a chart that comes out too small.

**Comment by jig78** [comment]
I figured it out. This is not related to the package. Thank you for quick reply!
