### ISSUE TITLE
Multiple outputs per code cell not supported

### ISSUE THREAD

**Issue by eliasmistler** [ideonate/nb2xls#5]
Thanks again for your fixes and quick response times.

I found another issue, this time related to multiple outputs, especially outputs of different mime types per cell.

The following could should display 5 headings and 5 tables. The xls sheet however only shows the latest table, and no headings:

```python
import pandas as pd
from IPython.display import *

for i in range(5):
    display(Markdown(f'# Markdown Loop {i}'))
    display(pd.DataFrame(pd.np.random.random((5,5))))
```

**Comment by danlester** [comment]
Thanks a lot - it was down to my misinterpretation of the nbformat spec, and ultimately no examples of this scenario. So thank you for providing the test case!

Released as version 0.1.5.

It would be great to find out more about how and why you're working with this project, so please do get in touch when you get a chance: dan@ideonate.com.
