### ISSUE TITLE
DOC: awesome-jupyterlab

### ISSUE THREAD

**Issue by westurner** [ideonate/nb2xls#7]
Cool extension. You might consider adding this and the other container DS Jupyter projects to awesome-jupyter, awesome-jupyterlab?

https://github.com/mauhai/awesome-jupyterlab

https://github.com/adebar/awesome-jupyter

https://github.com/quobit/awesome-python-in-education#jupyter

**Comment by danlester** [comment]
Thank you very much for the suggestion - will add it to my list!

Great to hear you like the extension.

**Comment by westurner** [comment]
Thanks!
